### ISSUE TITLE
Optionally add margin 

### ISSUE THREAD

**Issue by faroit** [GjjvdBurg/paper2remarkable#103]
`--no-crop` often is useful when users want to use the white space of the paper for annotations
`--blank` is useful for a lot of additional remarks

With the recent updates in 2.6 and the ability to quickly zoom, maybe a middle ground would make a good addition. I would propose a two step procedure

1. crop-off the margin like in the current default
2. optionally re-add a margin to the cropped page to either left or right side. This could for example be done as a percentage or as an absolute value.

**Comment by GjjvdBurg** [comment]
The default ``--crop`` option (and to a lesser extend the ``--right`` option) already crop with space left over for margin notes, no? The margins are defined [here](https://github.com/GjjvdBurg/paper2remarkable/blob/4b20e3da0ec89452e20ae54be8896055300cdf0f/paper2remarkable/crop.py#L75) so you could consider forking the project and changing the margins to a size that fits you.

**Comment by faroit** [comment]
> The margins are defined here so you could consider forking the project and changing the margins to a size that fits you.

sounds good, thanks
