### ISSUE TITLE
New source recommendations

### ISSUE THREAD

**Issue by mark-schultz** [GjjvdBurg/paper2remarkable#104]
I'd just quickly like to suggest two new sources that appear in theoretical computer science/cryptography, namely:

* IACR's Eprint: It is located at https://eprint.iacr.org/ . The format is that the abstract of a paper is contained at https://eprint.iacr.org/2021/489 , and the paper itself is found by appending .pdf to this https://eprint.iacr.org/2021/489.pdf
* ECCC: This is located at https://eccc.weizmann.ac.il/eccc/ . The most useful section of it is probably the `reports` section. A generic report is located at https://eccc.weizmann.ac.il/report/2021/052/ , and it can be downloaded by visiting https://eccc.weizmann.ac.il/report/2021/052/download .

**Comment by GjjvdBurg** [comment]
Thanks for the suggestions @mark-schultz, I'll see what I can do!

**Comment by GjjvdBurg** [comment]
These are now available in v0.9.4.
