### ISSUE TITLE
Suggestion: add example conversion to Readme.

### ISSUE THREAD

**Issue by ReinierKoops** [GjjvdBurg/paper2remarkable#105]
Hi Gertjan, love this tool. thank you for making it. Just as the title suggests, could you add a pdf conversion example image with default options enabled to the repository Readme?

**Comment by GjjvdBurg** [comment]
Hi Reinier, thanks for opening this issue, glad to hear you like the tool! 

Could you elaborate on what kind of image you have in mind? Would it show the reMarkable as well, or only how borders are removed? If you'd like to make it yourself I'd be happy to consider a pull request of course.

**Comment by ReinierKoops** [comment]
Sure, I'll make a pull request for it in a few days!
