### ISSUE TITLE
Can't get -p option (or --remarkable-path) to work

### ISSUE THREAD

**Issue by robfreundlich** [GjjvdBurg/paper2remarkable#131]
No matter what I try, the PDF file ends up in the `/` directory. Here's a sample session:

```
rob@Platinum:/mnt/e/downloads$ p2r -p /Tools temp.pdf
rob@Platinum:/mnt/e/downloads$ rmapi ls /Tools
Refreshing tree...
WARNING!!!
  Using the new 1.5 sync, this has not been fully tested yet!!!
  Make sure you have a backup, in case there is a bug that could cause data loss!
[f]     Shapes
rob@Platinum:/mnt/e/downloads$ rmapi ls /
Refreshing tree...
WARNING!!!
  Using the new 1.5 sync, this has not been fully tested yet!!!
  Make sure you have a backup, in case there is a bug that could cause data loss!
[d]     1 - Projects
[f]     Print Friendly & PDF
[f]     Quick sheets
[d]     3 - Resources
[d]     2 - Areas
[f]     temp
[d]     Tools
[d]     eBooks-Unread
[d]     eBooks-Read
[d]     4- Archives
rob@Platinum:/mnt/e/downloads$
```

Note that although I'm using a local file here, I started out using a URL and simplified down to the local file to minimize moving parts.

I'm running Ubuntu via WSL2 on Window 10.

**Comment by GjjvdBurg** [comment]
Hi @RobFreundlich,

Thanks for reporting this issue and sorry to hear you're having trouble. Can you try directly uploading to the Tools directory through rMapi? You can try that with this command:
```
rmapi put temp.pdf /Tools
```
If this doesn't work, can you please also try without a leading slash?
Thanks!

**Comment by RobFreundlich** [comment]
> > > Can you try directly uploading to the Tools directory through rMapi?
> > 
> > 
> > Yup. That works.
> 
> Just to clarify, does that place it in the /Tools directory or does that also place it in the root?

Using rMapi directly puts it in the /Tools directory.

**Comment by kahn-jms** [comment]
Howdy, it looks like the `remarkable_dir` argument isn't actually passed to the runner in `ui.py` in
https://github.com/GjjvdBurg/paper2remarkable/blob/master/paper2remarkable/ui.py#L337

Passing it there fixes this, though it looks like this should really be passed via `options`, though the `remarkable_dir` argument is currently missing from `merge_options` in `ui.py`.
