### ISSUE TITLE
support for providing a PDF directly as input?

### ISSUE THREAD

**Issue by bbolker** [GjjvdBurg/paper2remarkable#140]
This looks like a fantastic resource - looking forward to using it.

<wishlist>
Something that seems like it should be easy to implement (ha!), but might take me a while to accomplish with my rusty Python skills, would be to add a flag that allows short-circuiting the "look up and download step" and just doing the rest (crop/adjust/upload to RM) for a file taken from the local file system. 

This would be particularly nice as a partial solution/workaround to the "zoom-to-fit sucks since the updated to the new software" problem ...
</wishlist>

**Comment by bbolker** [comment]
PS the advice about installing rMAPI seems out of date "go.mod file not found in current directory or any parent directory.; 'go get' is no longer supported outside a module" I ended up downloading a Linux binary ... the github README says you can clone and install *or* download a binary ...

**Comment by GjjvdBurg** [comment]
Thanks for opening this issue @bbolker! Local file support already exists in the package, but perhaps wasn't clearly described in the README. I've added [a note](https://github.com/GjjvdBurg/paper2remarkable/blob/master/README.md?plain=1#L214) to highlight that both local PDF files and local Postscript files can be handled with the `p2r` script too. I've also updated the installation instructions for rMAPI, thank you for letting me know that they were outdated. If you encounter any issues with the local file functionality please reach out.

P.S. Thank you for making the [measles dataset](https://math.mcmaster.ca/~bolker/measdata.html) public, I've used it in [a paper](https://arxiv.org/abs/2003.06222) on change point detection a few years ago.
