### ISSUE TITLE
Issue with connecting rmapi

### ISSUE THREAD

**Issue by and-97** [GjjvdBurg/paper2remarkable#141]
Hi,
I followed all of the installation steps but i am having some issues in making `p2r` talk with `rmapi`. If i try to run 'p2r' with an arXiv link i get the message:
```shell
[Errno 2] No such file or directory: 'rmapi
``` 
Indicating that 'p2r' is not communicating correctly with 'rmapi', which is installed in '/homeandrea/rmapi'. I have tried giving this path to 'p2r' with the option mentioned in the readme:
```shell
p2r --rmapi /home/andrea/rmapi
```
But i get the following output:
```shell
usage: p2r [-h] [-b] [-c] [-d] [-e] [-n] [-p REMARKABLE_DIR] [-r] [-k] [-v]
           [-V] [-f FILENAME] [--gs GS] [--pdftoppm PDFTOPPM] [--pdftk PDFTK]
           [--qpdf QPDF] [--rmapi RMAPI] [--css CSS] [--font-urls FONT_URLS]
           [-C CONFIG]
           input [input ...]
p2r: error: the following arguments are required: input
```
I have tried different combinations, by including the final slash, or leaving it out, i have also tried to pass the path to the actual 'main.go' file i use to access rmapi functionalities.

What am i doing wrong here?

**Comment by GjjvdBurg** [comment]
Hi @and-97, thanks for opening this issue. When running `p2r --rmapi /home/andrea/rmapi`, don't forget to specify the arXiv url:
```
p2r --rmapi /home/andrea/rmapi https://arxiv.org/abs/1811.11242
```

**Comment by and-97** [comment]
Oh ok I see what the mix-up was: I thought that the ''--rmapi'' option allowed to permanently change the default ''rmapi'' folder for future executions of the program.

Is there a way to obtain just that? It would be far more comfortable than having to type it out every time or having to reinstall ''rmapi'' and reinstall it in the default path.

**Comment by GjjvdBurg** [comment]
Yes, you can use the configuration file as described in the README: https://github.com/GjjvdBurg/paper2remarkable/blob/master/README.md?plain=1#L216. The `rmapi` line would be similar to the `gs` example here: https://github.com/GjjvdBurg/paper2remarkable/blob/master/config.example.yml#L14

**Comment by GjjvdBurg** [comment]
Closing, please reopen if there are further questions!
