### ISSUE TITLE
URL regex fails for valid URL

### ISSUE THREAD

**Issue by Barabazs** [GjjvdBurg/paper2remarkable#151]
The current regex fails to validate 'https://hackmd.io/@abdelhamid/ethereum-alignment' as a valid URL.

I would suggest to replace the regex with a library like https://validators.readthedocs.io or fix the regex pattern. It might also be a good idea to add a `--source=url` type of option in the CLI.

PS: I can create a PR if you agree.

**Comment by GjjvdBurg** [comment]
Thanks for reporting this @Barabazs! Both of those sound like great ideas, and I'd welcome your PR!
