### ISSUE TITLE
Creating directory fails if doesn't exist

### ISSUE THREAD

**Issue by matthijsvk** [GjjvdBurg/paper2remarkable#20]
I'm trying to save papers to specific directories, but creating the directory fails if it doesn't exists.
If I manually create the directory on the Remarkable first, it works. 

I'm on version 2.0.2.0.

Command I used: 
`p2r https://arxiv.org/abs/1811.11242 -p /Testdir --filename test.pdf`

Error message: 
```
ERROR: 2020/01/09 15:22:36 main.go:17: Error:  directory doesn't exist
ERROR: Creating directory /testdir on reMarkable failed
Error occurred. Exiting.
```

**Comment by GjjvdBurg** [comment]
Hi @matthijsvk, thanks for reporting this issue! I think this is fixed now, and I'll prepare a new release of the package right away. Let me know if you encounter any further problems with the package!
