### ISSUE TITLE
upload to directory fails if file already exists in top-level 'My Files' directory

### ISSUE THREAD

**Issue by matthijsvk** [GjjvdBurg/paper2remarkable#22]
If I try to upload a file to some directory on the reMarkable with the '-p' option, and the file already exists in the top-level folder, the transfer fails.

Maybe the program first transfers the document to the remarkable in the top-level folder, and then moves it?

An alternative would be to rename it with some random name, transfer it, and then rename again when moving to the final directory.

Error message:

```
ERROR: 2020/01/10 14:01:09 main.go:17: Error:  entry already exists
Traceback (most recent call last):
  File "/usr/local/bin/p2r", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/paper2remarkable/__main__.py", line 13, in main
    sys.exit(realmain())
  File "/usr/local/lib/python3.7/site-packages/paper2remarkable/ui.py", line 127, in main
    prov.run(args.input, filename=args.filename)
  File "/usr/local/lib/python3.7/site-packages/paper2remarkable/providers/_base.py", line 124, in run
    rmapi_path=self.rmapi_path,
  File "/usr/local/lib/python3.7/site-packages/paper2remarkable/utils.py", line 124, in upload_to_remarkable
    "Uploading file %s to reMarkable failed" % filepath
paper2remarkable.exceptions.RemarkableError: ERROR: Uploading file document.pdf to reMarkable failed
```

**Comment by GjjvdBurg** [comment]
Thanks for reporting this @matthijsvk I'll take a look

**Comment by GjjvdBurg** [comment]
@matthijsvk I think this problem lies with rmapi, so I've raised an issue there.

**Comment by GjjvdBurg** [comment]
I'm closing this as it's an issue in rmapi.

**Comment by GjjvdBurg** [comment]
@matthijsvk this is now fixed in rmapi: https://github.com/juruen/rmapi/pull/95, thanks again for reporting!

**Comment by matthijsvk** [comment]
awesome, thanks :)
