### ISSUE TITLE
Default PDF Title

### ISSUE THREAD

**Issue by sirupsen** [GjjvdBurg/paper2remarkable#25]
Moving https://github.com/GjjvdBurg/paper2remarkable/commit/d4c682b869bb2bf391d5cf686baec026c5956875 here, good call @GjjvdBurg :)

Some papers, e.g. [this one](https://www.nber.org/papers/w26752.pdf) doesn't provide the author/title metadata for a nice title 😢 I've been using the "Print to Remarkable" Chrome extension, but recently started trying to use `p2r` via Alfred to transfer _all_ content to my reMarkable due to options like the blank pages between pages (brilliant idea, I've over-scribbled too many papers) and wanting to move to Firefox.

Some papers don't have this metadata. I think an option to use the pdf name (in the case above, `w26752.pdf`) as the default would be great for those uses, rather than raising :)

**Comment by GjjvdBurg** [comment]
This is a good point. Ideally, I'd prefer to add NBER as a Provider of papers (which is what I've done in #27) as it isn't too hard to add these providers and it's nice to have proper filenames.

But to address the issue, I think it's probably best to replace the error with a warning and use the pdf name where possible.

**Comment by GjjvdBurg** [comment]
Now fixed in master, I'll release a new version of the package asap. Thanks for your suggestions!

**Comment by sirupsen** [comment]
@GjjvdBurg you're so responsive, I love it!
