### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by sirupsen** [GjjvdBurg/paper2remarkable#26]
This is not overly a nuisance for me because I run the script async, but it does make it a little less pleasant to use. This 41 page PDF takes over one minute!

```
dotfiles $ time p2r https://www.nber.org/papers/w26752.pdf --filename test

real    1m4.323s
user    0m47.352s
sys     0m3.790s
```

**Comment by GjjvdBurg** [comment]
Hi @sirupsen, thanks for the bug reports! Yes, performance is a bit of an issue. The majority of the time is spent on cropping the pages of the pdf to remove excess white space. After some profiling it seems that the expensive part of that operation is creating an image of a pdf page using the pdfplumber package and I don't see a way to avoid that (the reason this is done in Python at all is that the bounding box returned by pdfcrop isn't very accurate (4cb3af83)).

I did just push a commit (a2e833ad) that speeds up using the ``--center`` flag, but you don't use that in your example.

Alternatively, I could add a ``--no-crop`` flag, which would speed up the process but lead to less nice results. Would that help?

**Comment by sirupsen** [comment]
Might it be possible to remove whitespace without converting to an image first? 👂

**Comment by GjjvdBurg** [comment]
I'm not sure, it might be necessary to render the pdf to figure out what the page looks like. That said, there is a pdfparser package that links directly to libpoppler, which seems a lot faster but is not a drop-in replacement for the current method with pdfplumber. I'll look into this a bit more and see what I can do.

**Comment by GjjvdBurg** [comment]
@sirupsen Thanks again for reporting this issue! I've just pushed some changes that give about an 8x speedup. I'll prepare a new release of the package soon.

**Comment by sirupsen** [comment]
Excellent!!! I’ll upgrade as soon as it’s released.

I do think a no crop flag would be useful. Some may prefer to have tools (change pen, highlight, etc) visible at all times — or perhaps the crop could leave just enough space to always have the tools available on the left side?

**Comment by GjjvdBurg** [comment]
> I do think a no crop flag would be useful. Some may prefer to have tools (change pen, highlight, etc) visible at all times — or perhaps the crop could leave just enough space to always have the tools available on the left side?

Try version 0.5.4, both a ``--no-crop`` and a ``--right`` option are now available! :)

**Comment by sirupsen** [comment]
😍
