### ISSUE TITLE
Processed pdfs seems to lag the remarkable

### ISSUE THREAD

**Issue by vberger** [GjjvdBurg/paper2remarkable#33]
First of all, thanks a lot for doing this tool, it is quite useful!

However, there seem to be some way in which it processes the PDFs that make them difficult to handle for my remarkable. This for example happens with this paper: https://arxiv.org/abs/2002.09339

If I copy the arXiv PDF directly on the remarkable, it has no trouble loading and displaying it, however when I process it with `p2r -c`, the resulting PDF seems to cause trouble to the tablet, notably:

- it does not display any thumbnail for it
- opening it and turning pages is slow (several seconds, sometimes up to 15-20s), to the point the tablet even show its 3 dots loading animation just to turn the page
- it seems to overall lag the tablet, even pressing the center button to close the PDF takes several seconds during which the tablet is basically unresponsive.

I also just tested and uploading the paper with `p2r --no-crop` causes the same issues.

**Comment by vberger** [comment]
After some more digging, it appears to be cause by the shrinking processing. Commenting this line makes the issue completely disappear:

https://github.com/GjjvdBurg/paper2remarkable/blob/74c0240b7022e199124acd8941d9fa3a1bea228f/paper2remarkable/providers/_base.py#L78

**Comment by GjjvdBurg** [comment]
Thanks for the detailed bug report @vberger! I've just updated the package to simply return the original version when the shrink operation returns a bigger filesize (see version 0.5.5).

Note that for the paper that you link to there is still a short delay for the page with the heatmap image, but that seems to just be a hard page to parse as even my normal pdf reader hangs for a while.
