### ISSUE TITLE
p2r asking for pdftk instead of using qpdf on ubuntu

### ISSUE THREAD

**Issue by nitin-ppnp** [GjjvdBurg/paper2remarkable#42]
I have kubuntu 18.04. When I run the example command 
`p2r -v https://arxiv.org/abs/1811.11242 `. It gives the error 
`[Errno 2] No such file or directory: 'pdftk': 'pdftk'`

**Comment by GjjvdBurg** [comment]
Thanks for reporting this @nitin-ppnp! Should be fixed now and I'll prepare an updated release right away.
