### ISSUE TITLE
Any article on a website

### ISSUE THREAD

**Issue by GliderGeek** [GjjvdBurg/paper2remarkable#44]
nice work on this tool.

i saw that you want to add the possibility to source from any website article. i just created a tool which takes URLs (from pocket read-later app) and create epubs for the remarkable: https://github.com/GliderGeek/pocket2rm. its written in go but there are plenty "readability" packages for python as well. hope this helps.

**Comment by GjjvdBurg** [comment]
Hi @GliderGeek, thanks for your message. I'm not quite sure I understand what you're suggesting, as paper2remarkable already supports transferring a web article. The package uses [readability-lxml](https://github.com/buriy/python-readability) to extract the text from a HTML source, does some cleaning, and then sends it to the reMarkable as a pdf.

**Comment by GliderGeek** [comment]
my bad, i saw it in the todo list in the readme so thought it was not present yet.

**Comment by GjjvdBurg** [comment]
No worries @GliderGeek! I appreciate that you tried to help!
