### ISSUE TITLE
Images for websites not included in PDF export

### ISSUE THREAD

**Issue by sirupsen** [GjjvdBurg/paper2remarkable#45]
Hello again Gertjan!

I was sending a long article this morning to my [Remarkable with p2r](https://conclave-team.github.io/conclave-site/) (I mostly use it for papers, so that's why I hadn't noticed this before), and unfortunately it seems that the images are lost :(

<img width="598" alt="image" src="https://user-images.githubusercontent.com/97400/80311708-294a8e80-87af-11ea-8f0e-50e8a6142694.png">

Versus the website:

<img width="919" alt="image" src="https://user-images.githubusercontent.com/97400/80311713-32d3f680-87af-11ea-81e1-915ac17acbe9.png">

**Comment by GjjvdBurg** [comment]
Thanks for reporting this issues @sirupsen! I think the fix in #47 ought to do it. I'll take a look at your other PR (#46) and prepare a release later today.

**Comment by GjjvdBurg** [comment]
This is now available in 0.6.3, thanks again for reporting.

P.S. I enjoyed reading your superorganizers interview :)

**Comment by sirupsen** [comment]
Thanks, glad you enjoyed it :)

I upgraded and tested this morning, still seems to have trouble.

For some reason it didn't work to try the same article, complaining about what I assume is a duplicate from `rmapi`. Although there's nothing to be found, searched in the reMarkable... odd. 

Tried another article, but it also appears without pictures.

```
dotfiles $ p2r https://conclave-team.github.io/conclave-site/
ERROR: 2020/04/28 07:55:44 main.go:17: Error:  entry already exists
ERROR: Uploading file Conclave_Case_Study_-_A_Private_and_Secure_Real-Time_Collaborative_Text_Editor.pdf to reMarkable failed

If you think this might be a bug, please raise an issue on GitHub at:
https://github.com/GjjvdBurg/paper2remarkable

dotfiles $ p2r https://sirupsen.com/2019/
```

<img width="536" alt="image" src="https://user-images.githubusercontent.com/97400/80484568-ef4fc880-8925-11ea-9b45-51759b130524.png">

Versus browser:

<img width="634" alt="image" src="https://user-images.githubusercontent.com/97400/80484594-f70f6d00-8925-11ea-8d60-45fdbb372091.png">

**Comment by GjjvdBurg** [comment]
Thanks for the update! 

The first problem sounds like it might be a duplicate of #22, perhaps try updating your rmapi version and see if that solves it?

The second problem is due to the trailing slash on the image source. For some reason the weasyprint package, which does the actual downloading of images, doesn't deal with that well (same goes for `wget` on the command line, apparently). Simply stripping it seems to solve the problem (#48).
