### ISSUE TITLE
Some images do not get picked up

### ISSUE THREAD

**Issue by sirupsen** [GjjvdBurg/paper2remarkable#53]
I have started sending newspaper articles to my Remarkable a lot more, passing it through `p2r`, since the output is much nicer and more consistent than a print-to-pdf.

However, some websites have trouble with images. I was debugging it a bit this morning, but had to step away before finding a solution.

Here's an example of [an article](https://www.economist.com/united-states/2020/06/04/how-to-fix-american-policing) that exhibits the problem (if you get pay-walled, you can see it below using the `<figure>` syntax).

![image](https://user-images.githubusercontent.com/97400/84571874-47bb1800-ad64-11ea-8bbc-8df098ad7acb.png)

After digging a bit in the code, it seems that this is a problem in `html2text`, where it doesn't seem to pick up these `<figure>` tags, since if you pass `--debug`, the `.html` file doesn't include the images either.

There's probably a few solutions... the hackiest, but quickest, would be to regex these out and insert them into the string as 'simple' images that `html2text` would pick up. The more elegant, but also more time-consuing, would be to have `html2text` support [`<figure>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure) properly.

**Comment by GjjvdBurg** [comment]
Thanks for reporting this @sirupsen, I'll try to take a look soon

**Comment by sirupsen** [comment]
BTW @GjjvdBurg do you have anywhere set up where I can donate/sponsor? Use `paper2remarkable` a lot for generating clean PDFs, least I could do :)

**Comment by GjjvdBurg** [comment]
> BTW @GjjvdBurg do you have anywhere set up where I can donate/sponsor? Use `paper2remarkable` a lot for generating clean PDFs, least I could do :)

Thanks for the suggestion @sirupsen! I don't currently have anything set up, but I'll consider doing so. 

So I've been looking into this and I can't figure out why _some_ figure tags get interpreted correctly and others don't. I got paywalled on the article you quoted above, but the same seems to happen on articles on Medium or some newspapers (such as Der Spiegel). Images on those articles don't get passed through, whereas those in, for instance, [this article](https://www.nature.com/articles/d41586-020-00176-4), are interpreted fine.

The problem, as far as I've been able to track it down, is in readabilty. This seems to be [a known issue](https://github.com/buriy/python-readability/issues/121) there, but I'm not sure how likely it is that a fix will be released soon.

An alternative would be to skip readability (optionally, perhaps) and pass the original HTML to html2text, but that does seem to add a lot more noise to the generated Markdown.

I'll think about this a bit more, but if you have any ideas please let me know.

**Comment by sirupsen** [comment]
One quick idea would be to see if the Javascript (which is maintained by Mozilla) readability has the same issue, and then shell out to it (or embed V8, which I know at least is commonly done in Ruby for asset compilation). Not ideal...

**Comment by GjjvdBurg** [comment]
I think I've found a fix! :smile: 

The Alan Turing Institute actually happens to have a project that wraps Readability.js, called [ReadabiliPy](https://github.com/alan-turing-institute/ReadabiliPy). This isn't available as a Python package yet (until alan-turing-institute/ReadabiliPy#86 is merged), but seems to be a feasible solution.

If you'd like to try it out, currently the steps are as follows:
1. Ensure you have [npm](www.npmjs.com) and node installed
2. Install paper2remarkable from the PR branch #54, using ``pip install .[full]`` (this pulls in ReadabiliPy).

I've found only a few sites that seem to behave similarly to what you reported (one is now a unit test in #54), so it'd be great if you can test it out.

**Comment by sirupsen** [comment]
Oh that's awesome! Unfortunately my Remarkable just broke.... so it'll be about 2 months (given the ridiculous schedule their warranty operates under) until I have one again. I ended up buying an iPad, because the flow of having a device for reading very dense articles is critical to me now.

**Comment by GjjvdBurg** [comment]
Ouch, that's too bad, hope you can get a replacement soon!

**Comment by GjjvdBurg** [comment]
Hi @sirupsen, I've just pushed a new version of paper2remarkable that optionally uses Readability.js to extract the html article, which appears to solve the problem of missing images. Hope you're able to give it a try!
