### ISSUE TITLE
If the arxiv link looks like  "http://arxiv.org/abs/arXiv:1908.03213", link not recognised 

### ISSUE THREAD

**Issue by aweiler** [GjjvdBurg/paper2remarkable#7]
Some arxiv links on e.g. inspire (see e.g. [link](https://inspirehep.net/search?p=find+eprint+1908.03213) ) are of this form
```
http://arxiv.org/abs/arXiv:1908.03213
```
which leads to this:
```
ERROR: Filename must be provided with PDFUrlProvider (use --filename)
Error occurred. Exiting.

2019-10-07 16:35:24 - INFO - Starting PdfUrl
If you think this might be a bug, please raise an issue on GitHub: https://github.com/GjjvdBurg/arxiv2remarkable
```

**Comment by GjjvdBurg** [comment]
This bug is fixed in version 0.4.1 of paper2remarkable (I changed the name recently). Thanks for your patience on this and let me know if you have any further problems or feature requests!
