### ISSUE TITLE
not taking the remarkable 8 char key

### ISSUE THREAD

**Issue by DOFfactory** [GjjvdBurg/paper2remarkable#73]
Trying to follow the instructions on the docker build, however, whenever I enter the 8-char password, the website says "Success!"., while the command line keeps asking for a new code... Can you please assist in trouble-shooting?

When I try to run the container, I get the error `ERROR: 2020/11/06 13:29:24 auth.go:64: Code has the wrong length, it should be 8`

**Comment by GjjvdBurg** [comment]
Hi @DOFfactory,

Sorry to hear you're having trouble with the authentication. First things first, did you check that the code you entered is indeed 8 characters? No spaces or anything?

The next thing to check is that you've used the correct commands. Did you run the following lines exactly for the authentication?

```
touch ${HOME}/.rmapi
docker run --rm -i -t -v "${HOME}/.rmapi:/home/user/.rmapi:rw" --entrypoint=rmapi p2r version
```

**Comment by DOFfactory** [comment]
Hi @GjjvdBurg, thanks for the follow-up, there was an error in my path in the command, so it was a false alarm. Now it works, however, the instructions might be a bit clearer for the docker, as not everybody is setting up the .rmapi in their ${HOME}. Closing, works nicely, thanks for putting this together!

**Comment by GjjvdBurg** [comment]
Hi @DOFfactory, thanks for letting me know that you got it working! 

If you have suggestions for how to improve the documentation I'd love to hear it. I think the ``touch ${HOME}/.rmapi`` line is used because ``rMapi`` checks there first. I guess your suggestion is to also mention the ``${HOME}/.config/rmapi`` option?

**Comment by DOFfactory** [comment]
I see, I am not familiar too much with the rmapi tool, I just have a dedicated path for every docker container I use, and I needed to use that instead. After little fiddling with the path it started to work. That being said, it was quite difficult to troubleshoot, what was the issue, so it might be useful to identify why the rmapi is asking again-and-again for the 8 character password, while the website says "Success"... Will think about how to help and provide the requested suggestion.

**Comment by GjjvdBurg** [comment]
Thanks @DOFfactory, I'd appreciate the help. I don't use the docker approach myself, so getting insight from new users on how to improve the documentation is very valuable.

I've just expanded the section on [authentication](https://github.com/GjjvdBurg/paper2remarkable#authorization) to provide some more details. Hopefully this makes the instructions clearer but I'd appreciate your feedback!

**Comment by DOFfactory** [comment]
One more thing: is there a way for the alias, how to add for example the `--right` argument by default to `p1r` of the docker command? I tried almost anything with the alias, and it does not work. I would love to avoid typing it every time to the CLI

**Comment by GjjvdBurg** [comment]
I can't test right now, but does this work?

```
alias p2r="docker run --rm -v \"${HOME}/.rmapi:/home/user/.rmapi:rw\" p2r -r"
```

Or maybe:

```
alias p2r="docker run --rm -v \"${HOME}/.rmapi:/home/user/.rmapi:rw\" --entrypoint=\"p2r -r\" p2r"
```

**Comment by DOFfactory** [comment]
Thanks @GjjvdBurg, tried both, none of them is working as intended. Somehow it ignores the `-r` argument, no idea why

**Comment by GjjvdBurg** [comment]
I've just tested it here with:

```bash
# in .bashrc
alias p2r="docker run --rm -v \"${HOME}/.rmapi:/home/user/.rmapi:rw\" p2r -r -n -v"
```
(using ``-n`` to disable uploading while testing). Running it gives:

```
[user@hostname] $ p2r https://arxiv.org/abs/2003.06222
2020-11-09 12:45:04 - INFO - Starting Arxiv provider
2020-11-09 12:45:04 - INFO - Generating output filename
2020-11-09 12:45:04 - INFO - Getting paper info
2020-11-09 12:45:05 - INFO - Downloaded url: https://arxiv.org/abs/2003.06222
2020-11-09 12:45:05 - INFO - Created filename: Burg_Williams_-_An_Evaluation_of_Change_Point_Detection_Algorithms_2020.pdf
2020-11-09 12:45:05 - INFO - Downloading file at url: https://arxiv.org/pdf/2003.06222.pdf
2020-11-09 12:45:26 - INFO - Downloaded url: https://arxiv.org/pdf/2003.06222.pdf
2020-11-09 12:45:26 - INFO - Removing arXiv timestamp ... success
2020-11-09 12:45:31 - INFO - Preparing PDF using right operation
2020-11-09 12:45:32 - INFO - Processing pages ... (10/33)
2020-11-09 12:45:32 - INFO - Processing pages ... (20/33)
2020-11-09 12:45:34 - INFO - Processing pages ... (30/33)
2020-11-09 12:45:34 - INFO - Processing pages ... (33/33)
2020-11-09 12:45:34 - INFO - Shrinking pdf file ...
```

Note that the line saying the "right operation" is used. I'm not sure why it wouldn't work for you. Are you sure the docker version is used when you run ``p2r``? Try double checking with ``$ type p2r``. If you have it installed on your system directly that may cause conflicts.

**Comment by DOFfactory** [comment]
Haha, it was initially not working, but a simple logout-logon helped. I guess bash does not check the changes in .bashrc only after logon. Thanks for helping with the troubleshooting.

**Comment by GjjvdBurg** [comment]
Ah right, yeah the alternative is to source your .bashrc using ``source .bashrc``. Glad you got it working!
