### ISSUE TITLE
Error on auth.go, Docker version

### ISSUE THREAD

**Issue by muhark** [GjjvdBurg/paper2remarkable#75]
I realise that this may be a bug on the rmapi side, but thought it would be good to bring to your intention.

I'm trying to use the docker version of this application and for every file I try to download/upload, I run into the following error:

```
ERROR: 2020/11/11 23:06:36 auth.go:64: Code has the wrong length, it should be 8
```

System: Fedora 32
Device: Remarkable 2

Let me know what else you might need. As far as I can tell this happens right after removing the timestamp.

I'd also be happy to help where I can--I'm pretty comfortable with Python.

**Comment by muhark** [comment]
Ah wait looking at the go code now, I think it may be an issue with my config.

**Comment by muhark** [comment]
Have raised an issue on rmapi.

**Comment by GjjvdBurg** [comment]
Is your problem perhaps related to #73?

**Comment by GjjvdBurg** [comment]
Closing this, please reopen if necessary.
