### ISSUE TITLE
pdf timetables

### ISSUE THREAD

**Issue by AlamOs04** [GjjvdBurg/paper2remarkable#80]
When cropping a document the timetable isn't present in the output file. Since all pages from the original file are kept (even the empty ones), would it be possible to keep the timetable or add it afterwards?

**Comment by GjjvdBurg** [comment]
Thanks for reporting this @AlamOs04! I'm assuming you mean the table of contents? This is indeed not preserved at the moment, but I'll see what I can do.

**Comment by GjjvdBurg** [comment]
Fixed in #94 thanks to @Kazy, please update to v0.9.0 of the package to use this feature.
