### ISSUE TITLE
Custom font and line-spacing

### ISSUE THREAD

**Issue by teranex** [GjjvdBurg/paper2remarkable#82]
When fetching an URL, is it somehow possible to specify the font (or font family) to use and specify the line-spacing? When possible I prefer reading articles in a serif font and with a larger line spacing.

**Comment by GjjvdBurg** [comment]
Hi @teranex, thanks for the suggestion! I've just added support for providing your own CSS to style the HTML output. I'll prepare a new release of the package right away.

For now you'll have to supply the css/font urls to the script using command line flags, but I'm thinking of adding support for a configuration file in the future, which would hopefully make this a smoother experience.

Let me know if you run into any issues using the new feature!

**Comment by GjjvdBurg** [comment]
The program now has support for providing a configuration file where the custom css and fonts can be specified. Please check the readme for more info.

**Comment by teranex** [comment]
This works. Thanks a lot!
