### ISSUE TITLE
Error Building wheel for paper2remarkable (PEP 517)

### ISSUE THREAD

**Issue by charlie-cummings** [GjjvdBurg/paper2remarkable#86]
To preface, I'm a physics student so I'm not an expert at this stuff so I apologize if this is a very simple issue.

I am using Python 3.6, and pip, setuptools, wheels are fully updated. I am running an Ubuntu 18.04 subsystem on Windows 10. I have all the dependencies (rMAPI, etc) installed.

When I run `pip install paper2remarkable`, where paper2remarkable is the path to my local installation of the repo, I get the following error message:

> Building wheels for collected packages: paper2remarkable
>  **Building wheel for paper2remarkable (PEP 517) ... error
>  ERROR: Command errored out with exit status 1:
>   command: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py build_wheel/tmp/tmpmaiapbt0**
>       cwd: /tmp/pip-req-build-t42w8_q6
 > Complete output (97 lines):
 >running bdist_wheel
  >running build
  >running build_py
 > creating build
 > creating build/lib
 > creating build/lib/paper2remarkable
 > copying paper2remarkable/__init__.py -> build/lib/paper2remarkable
 > copying paper2remarkable/__main__.py -> build/lib/paper2remarkable
 > copying paper2remarkable/__version__.py -> build/lib/paper2remarkable
 > copying paper2remarkable/crop.py -> build/lib/paper2remarkable
 > copying paper2remarkable/exceptions.py -> build/lib/paper2remarkable
 > copying paper2remarkable/log.py -> build/lib/paper2remarkable
 > copying paper2remarkable/pdf_ops.py -> build/lib/paper2remarkable
 > copying paper2remarkable/ui.py -> build/lib/paper2remarkable
 > copying paper2remarkable/utils.py -> build/lib/paper2remarkable
 > creating build/lib/paper2remarkable/providers
 > copying paper2remarkable/providers/__init__.py -> build/lib/paper2remarkable/providers
 > copying paper2remarkable/providers/_base.py -> build/lib/paper2remarkable/providers
 > copying paper2remarkable/providers/_info.py -> build/lib/paper2remarkable/providers
 > copying paper2remarkable/providers/acm.py -> build/lib/paper2remarkable/providers
 > copying paper2remarkable/providers/arxiv.py -> build/lib/paper2remarkable/providers
 > copying paper2remarkable/providers/citeseerx.py -> build/lib/paper2remarkable/providers
 > copying paper2remarkable/providers/cvf.py -> build/lib/paper2remarkable/providers
 > copying paper2remarkable/providers/html.py -> build/lib/paper2remarkable/providers
 > copying paper2remarkable/providers/jmlr.py -> build/lib/paper2remarkable/providers
 > copying paper2remarkable/providers/local.py -> build/lib/paper2remarkable/providers
 > copying paper2remarkable/providers/nature.py -> build/lib/paper2remarkable/providers
 > copying paper2remarkable/providers/nber.py -> build/lib/paper2remarkable/providers
 > copying paper2remarkable/providers/neurips.py -> build/lib/paper2remarkable/providers
 > copying paper2remarkable/providers/openreview.py -> build/lib/paper2remarkable/providers
 > copying paper2remarkable/providers/pdf_url.py -> build/lib/paper2remarkable/providers
 > copying paper2remarkable/providers/pmlr.py -> build/lib/paper2remarkable/providers
 > copying paper2remarkable/providers/pubmed.py -> build/lib/paper2remarkable/providers
 > copying paper2remarkable/providers/sagepub.py -> build/lib/paper2remarkable/providers
 > copying paper2remarkable/providers/science_direct.py -> build/lib/paper2remarkable/providers
 > copying paper2remarkable/providers/semantic_scholar.py -> build/lib/paper2remarkable/providers
 > copying paper2remarkable/providers/springer.py -> build/lib/paper2remarkable/providers
 > copying paper2remarkable/providers/tandfonline.py -> build/lib/paper2remarkable/providers
 > running egg_info
 > writing paper2remarkable.egg-info/PKG-INFO
 > writing dependency_links to paper2remarkable.egg-info/dependency_links.txt
 > writing entry points to paper2remarkable.egg-info/entry_points.txt
 > writing requirements to paper2remarkable.egg-info/requires.txt
 > writing top-level names to paper2remarkable.egg-info/top_level.txt
 > reading manifest file 'paper2remarkable.egg-info/SOURCES.txt'
 > reading manifest template 'MANIFEST.in'
 > warning: no files found matching 'p2r.1'
 > warning: no previously-included files found matching 'Makefile'
 > warning: no previously-included files found matching '.gitignore'
 > warning: no previously-included files found matching 'Dockerfile'
 > warning: no previously-included files found matching 'make_release.py'
 > no previously-included directories found matching 'old'
 > writing manifest file 'paper2remarkable.egg-info/SOURCES.txt'
 > installing to build/bdist.linux-x86_64/wheel
 > running install
 > running install_lib
 > creating build/bdist.linux-x86_64
 > creating build/bdist.linux-x86_64/wheel
 > creating build/bdist.linux-x86_64/wheel/paper2remarkable
 > copying build/lib/paper2remarkable/__init__.py -> build/bdist.linux-x86_64/wheel/paper2remarkable
 > copying build/lib/paper2remarkable/__main__.py -> build/bdist.linux-x86_64/wheel/paper2remarkable
 > copying build/lib/paper2remarkable/__version__.py -> build/bdist.linux-x86_64/wheel/paper2remarkable
 > copying build/lib/paper2remarkable/crop.py -> build/bdist.linux-x86_64/wheel/paper2remarkable
 > copying build/lib/paper2remarkable/exceptions.py -> build/bdist.linux-x86_64/wheel/paper2remarkable
 > copying build/lib/paper2remarkable/log.py -> build/bdist.linux-x86_64/wheel/paper2remarkable
 > copying build/lib/paper2remarkable/pdf_ops.py -> build/bdist.linux-x86_64/wheel/paper2remarkable
 > creating build/bdist.linux-x86_64/wheel/paper2remarkable/providers
 > copying build/lib/paper2remarkable/providers/__init__.py -> build/bdist.linux-x86_64/wheel/paper2remarkable/providers
>  copying build/lib/paper2remarkable/providers/_base.py -> build/bdist.linux-x86_64/wheel/paper2remarkable/providers
>   copying build/lib/paper2remarkable/providers/_info.py -> build/bdist.linux-x86_64/wheel/paper2remarkable/providers
>   copying build/lib/paper2remarkable/providers/acm.py -> build/bdist.linux-x86_64/wheel/paper2remarkable/providers
>   copying build/lib/paper2remarkable/providers/arxiv.py -> build/bdist.linux-x86_64/wheel/paper2remarkable/providers
>   copying build/lib/paper2remarkable/providers/citeseerx.py -> build/bdist.linux-x86_64/wheel/paper2remarkable/providers
>   copying build/lib/paper2remarkable/providers/cvf.py -> build/bdist.linux-x86_64/wheel/paper2remarkable/providers
>   copying build/lib/paper2remarkable/providers/html.py -> build/bdist.linux-x86_64/wheel/paper2remarkable/providers
>   copying build/lib/paper2remarkable/providers/jmlr.py -> build/bdist.linux-x86_64/wheel/paper2remarkable/providers
>   copying build/lib/paper2remarkable/providers/local.py -> build/bdist.linux-x86_64/wheel/paper2remarkable/providers
>   copying build/lib/paper2remarkable/providers/nature.py -> build/bdist.linux-x86_64/wheel/paper2remarkable/providers
>   copying build/lib/paper2remarkable/providers/nber.py -> build/bdist.linux-x86_64/wheel/paper2remarkable/providers
>   copying build/lib/paper2remarkable/providers/neurips.py -> build/bdist.linux-x86_64/wheel/paper2remarkable/providers
>   copying build/lib/paper2remarkable/providers/openreview.py -> build/bdist.linux-x86_64/wheel/paper2remarkable/providers
>   copying build/lib/paper2remarkable/providers/pdf_url.py -> build/bdist.linux-x86_64/wheel/paper2remarkable/providers
>   copying build/lib/paper2remarkable/providers/pmlr.py -> build/bdist.linux-x86_64/wheel/paper2remarkable/providers
>   copying build/lib/paper2remarkable/providers/pubmed.py -> build/bdist.linux-x86_64/wheel/paper2remarkable/providers
>   copying build/lib/paper2remarkable/providers/sagepub.py -> build/bdist.linux-x86_64/wheel/paper2remarkable/providers
>   copying build/lib/paper2remarkable/providers/science_direct.py -> build/bdist.linux-x86_64/wheel/paper2remarkable/providers
>   copying build/lib/paper2remarkable/providers/semantic_scholar.py -> build/bdist.linux-x86_64/wheel/paper2remarkable/providers
>   copying build/lib/paper2remarkable/providers/springer.py -> build/bdist.linux-x86_64/wheel/paper2remarkable/providers
>   copying build/lib/paper2remarkable/providers/tandfonline.py -> build/bdist.linux-x86_64/wheel/paper2remarkable/providers
>   copying build/lib/paper2remarkable/ui.py -> build/bdist.linux-x86_64/wheel/paper2remarkable
>   copying build/lib/paper2remarkable/utils.py -> build/bdist.linux-x86_64/wheel/paper2remarkable
>   running install_data
>   creating build/bdist.linux-x86_64/wheel/paper2remarkable-0.8.6.data
>   creating build/bdist.linux-x86_64/wheel/paper2remarkable-0.8.6.data/data
>   creating build/bdist.linux-x86_64/wheel/paper2remarkable-0.8.6.data/data/man
>   creating build/bdist.linux-x86_64/wheel/paper2remarkable-0.8.6.data/data/man/man1
>   **error: can't copy 'p2r.1': doesn't exist or not a regular file
>   ERROR: Failed building wheel for paper2remarkable
> Failed to build paper2remarkable
> ERROR: Could not build wheels for paper2remarkable which use PEP 517 and cannot be installed directly**

I've run out of luck with Google and figured I'd ask directly here. I can't seem to find a p2r.1 anywhere and I'm not sure where to go from here. Any help? Thanks!

**Comment by GjjvdBurg** [comment]
Hi @charlie-cummings, thanks for reporting this issue, I'm sorry to hear you're having trouble with the installation.

You mention that you're running ``pip install paper2remarkable`` on a local installation (clone) of the repository. This might be confusing the package source for pip, as it shouldn't be necessary to clone the repository prior to installation.

Could you try running ``pip install paper2remarkable`` directly, not inside a local copy of the repository? This should cause pip to download the necessary files from the internet (specifically, pypi).

Please let me know if that works, if it doesn't we can look further :)

**Comment by charlie-cummings** [comment]
Update: this did work.

I had tried this first (because that's what the instructions said) but it didn't work: it said it couldn't find the package. I live in a rural area and so I'm not gonna discount it was just my internet that was the issue! Additionally, I think my journey to fix it led me to update many things that needed updating that led it to work. Sorry for taking up your time with such an easy fix!

**Comment by GjjvdBurg** [comment]
No problem @charlie-cummings, glad to hear you got it to work!
